In [ ]:
# default_exp numpycore

# numpy 100题

In [ ]:
#hide
from nbdev.showdoc import *

1. 导入numpy库并简写为 np

In [ ]:
#export
import numpy as np

2. 打印numpy的版本和配置说明

In [ ]:
#hide
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. 创建一个长度为10的空向量

In [ ]:
#hide
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小

In [ ]:
#hide
print(f"{Z.size * Z.itemsize:d} bytes")

80 bytes


5. 如何从命令行得到numpy中add函数的说明文档

In [ ]:
#hide
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

6. 创建一个长度为10并且除了第五个值为1的空向量

In [ ]:
#hide
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [ ]:
#hide
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. 反转一个向量(第一个元素变为最后一个) 

In [ ]:
#hide
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [ ]:
#hide
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [ ]:
#hide
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. 创建一个 3x3 的单位矩阵

In [ ]:
#hide
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组

In [ ]:
#hide
Z = np.random.random((3,3,3))
print(Z)

[[[0.9185746  0.39025739 0.02692332]
  [0.32066755 0.05667642 0.7676012 ]
  [0.36968313 0.84252402 0.94829314]]

 [[0.85968162 0.16792748 0.23260453]
  [0.42205213 0.00964948 0.87070763]
  [0.10531112 0.82753313 0.62919363]]

 [[0.04950005 0.9570073  0.81993933]
  [0.8677428  0.88855734 0.81681692]
  [0.39252249 0.21686074 0.5272504 ]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [ ]:
#hide
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(f"min:{Zmin} max:{Zmax}")

min:0.004949720559430326 max:0.99591702949498


14. 创建一个长度为30的随机向量并找到它的平均值

In [ ]:
#hide
Z = np.random.random(30)
mean = Z.mean()
print(mean)

0.46453478136344434


15. 创建一个二维数组，其中边界值为1，其余值为0

In [ ]:
#hide
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在的数组，如何添加一个用0填充的边界

In [ ]:
#hide
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode="constant", constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么

In [ ]:
#hide
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [ ]:
#hide
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [ ]:
#hide
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么

In [ ]:
#hide
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [ ]:
#hide
Z = np.array([[0,1],[1,0]])
Z = np.tile(Z, (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化  
归一化:$（x-min）\div (max -min)$

In [ ]:
#hide
Z = np.random.random((5,5))
Zmax, Zmin = Z.min(), Z.max()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[ 0.30885376  1.          0.29868019  0.2628482   0.62237796]
 [ 0.17156351  0.03769223  0.1300209   0.38740392  0.80971789]
 [ 0.51227006  0.84954418  0.94229426  0.56217539  0.99532956]
 [ 0.22573165  0.78561604  0.39018087  0.21576756  0.50477359]
 [ 0.2394752  -0.          0.6423077   0.55088067  0.89172755]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义 dtype

In [ ]:
#hide
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [ ]:
#hide
Z = np.dot(np.ones((5,3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [ ]:
#hide
Z = np.arange(11)
Z[(3 < Z) & (8 >= Z)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么

In [ ]:
#hide
print(sum(range(5),-1))

9


In [ ]:
#hide
from numpy import *
print(sum(range(5),-1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个

In [ ]:
#hide
Z = np.arange(5)
Z ** Z

array([  1,   1,   4,  27, 256])

In [ ]:
#hide
Z = np.arange(5)
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [ ]:
#hide
Z = np.arange(5)
Z <- Z 

array([False, False, False, False, False])

In [ ]:
#hide
Z = np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [ ]:
#hide
Z = np.arange(5)
#Z<Z>Z

28. 下列表达式的结果分别是什么

In [ ]:
#hide
print(np.array(0) / np.array(0))

nan


In [ ]:
#hide
print(np.array(0) // np.array(0))

0


In [ ]:
#hide
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29. 如何从零位对浮点数组做舍入

In [ ]:
#hide
Z = np.random.uniform(-10, 10, 10)
print(Z)
absZ = np.abs(Z)
print(absZ)
ceilZ = np.ceil(absZ)
print(ceilZ)
csZ = np.copysign(ceilZ, Z)
print(csZ)

[-0.30304611  7.70249955  2.21103469 -0.18815923 -6.47994485 -4.38789418
 -0.64723942 -5.55099645  1.76711758  1.98614895]
[0.30304611 7.70249955 2.21103469 0.18815923 6.47994485 4.38789418
 0.64723942 5.55099645 1.76711758 1.98614895]
[1. 8. 3. 1. 7. 5. 1. 6. 2. 2.]
[-1.  8.  3. -1. -7. -5. -1. -6.  2.  2.]


30. 如何找到两个数组中的共同元素

In [ ]:
#hide
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1,Z2))

[1 2 3 6 7]


31. 如何忽略所有的 numpy 警告

In [ ]:
#hide
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
np.seterr(all=None)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

32. 下面的表达式是正确的吗

In [ ]:
#hide
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. 如何得到昨天，今天，明天的日期

In [ ]:
#hide
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"yesterday is {yesterday}")
print(f"today is {today}")
print(f"tomorrow is {tomorrow}")

yesterday is 2020-03-24
today is 2020-03-25
tomorrow is 2020-03-26


34. 如何得到所有与2016年7月对应的日期

In [ ]:
#hide
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [ ]:
#hide
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分

In [ ]:
#hide
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z-1))
print(Z.astype(int))
print(np.trunc(Z))

[2. 2. 9. 4. 8. 4. 3. 0. 5. 2.]
[2. 2. 9. 4. 8. 4. 3. 0. 5. 2.]
[ 2.  2.  9.  4.  8.  4.  3. -0.  5.  2.]
[2 2 9 4 8 4 3 0 5 2]
[2. 2. 9. 4. 8. 4. 3. 0. 5. 2.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [ ]:
#hide
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [ ]:
#export
def generate():
    for x in range(10):
        yield x

In [ ]:
#hide
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [ ]:
#hide
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序

In [ ]:
#hide
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0633654  0.17122567 0.27746292 0.32488084 0.39254657 0.46873914
 0.56779768 0.74197885 0.96006592 0.97971941]


41. 对于一个小数组，如何用比 np.sum更快的方式对其求和

In [ ]:
#hide
Z = np.arange(10)
np.add.reduce(Z)

45

42. 对于两个随机数组A和B，检查它们是否相等

In [ ]:
#hide
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A, B)
print(equal)
equal = np.array_equal(A, B)
print(equal)

False
False


43. 创建一个只读数组(read-only)

In [ ]:
#hide
Z: ndarray = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [ ]:
#hide
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.92834119 1.03200424 0.871882   0.82998107 1.13418503 1.01705383
 0.47791795 0.76626607 0.67061631 1.05813637]
[0.0085225  1.0977043  1.30770892 1.05304042 0.91133016 1.26400417
 0.34955451 1.32636672 1.52382612 0.6682605 ]


45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [ ]:
#hide
Z = np.random.random(10)
Z[Z.argmax()] = 1
print(Z)

[0.01954351 1.         0.73929144 0.31980815 0.81648214 0.26024465
 0.22529618 0.41610266 0.2702721  0.16812901]


46.  创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [ ]:
#hide
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
