In [ ]:
# default_exp numpycore

# numpy 100题

In [ ]:
#hide
from nbdev.showdoc import *

1. 导入numpy库并简写为 np

In [ ]:
#export
import numpy as np

2. 打印numpy的版本和配置说明

In [ ]:
#hide
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. 创建一个长度为10的空向量

In [ ]:
#hide
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小

In [ ]:
#hide
print(f"{Z.size * Z.itemsize:d} bytes")

80 bytes


5. 如何从命令行得到numpy中add函数的说明文档

In [ ]:
#hide
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

6. 创建一个长度为10并且除了第五个值为1的空向量

In [ ]:
#hide
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [ ]:
#hide
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. 反转一个向量(第一个元素变为最后一个) 

In [ ]:
#hide
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [ ]:
#hide
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [ ]:
#hide
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. 创建一个 3x3 的单位矩阵

In [ ]:
#hide
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组

In [ ]:
#hide
Z = np.random.random((3,3,3))
print(Z)

[[[0.81226495 0.23393644 0.99856697]
  [0.57464969 0.53405379 0.91272778]
  [0.40668142 0.28433399 0.40712555]]

 [[0.92197534 0.02884748 0.28846335]
  [0.65527404 0.67636101 0.65265031]
  [0.66744908 0.44716625 0.46342186]]

 [[0.37877384 0.91968361 0.50470942]
  [0.59973005 0.81367372 0.42228716]
  [0.9523315  0.29473268 0.2889548 ]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [ ]:
#hide
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(f"min:{Zmin} max:{Zmax}")

min:0.003741253324784366 max:0.9914868764632366


14. 创建一个长度为30的随机向量并找到它的平均值

In [ ]:
#hide
Z = np.random.random(30)
mean = Z.mean()
print(mean)

0.4895212423309116


15. 创建一个二维数组，其中边界值为1，其余值为0

In [ ]:
#hide
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在的数组，如何添加一个用0填充的边界

In [ ]:
#hide
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode="constant", constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么

In [ ]:
#hide
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [ ]:
#hide
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [ ]:
#hide
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么

In [ ]:
#hide
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [ ]:
#hide
Z = np.array([[0,1],[1,0]])
Z = np.tile(Z, (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化  
归一化:$（x-min）\div (max -min)$

In [ ]:
#hide
Z = np.random.random((5,5))
Zmax, Zmin = Z.min(), Z.max()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[ 0.73229977  0.21220789  0.57373311  0.31934148  0.63098421]
 [ 0.78232295  0.43832946  0.11029837  0.26574688  0.27710329]
 [ 0.99409704 -0.          1.          0.48094016  0.46171612]
 [ 0.89790734  0.28736873  0.32319906  0.31483138  0.9918128 ]
 [ 0.6807093   0.92340696  0.86560469  0.62714879  0.79974979]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义 dtype

In [ ]:
#hide
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [ ]:
#hide
Z = np.dot(np.ones((5,3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [ ]:
#hide
Z = np.arange(11)
Z[(3 < Z) & (8 >= Z)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么

In [ ]:
#hide
print(sum(range(5),-1))

9


In [ ]:
#hide
from numpy import *
print(sum(range(5),-1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个

In [ ]:
#hide
Z = np.arange(5)
Z ** Z

array([  1,   1,   4,  27, 256])

In [ ]:
#hide
Z = np.arange(5)
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [ ]:
#hide
Z = np.arange(5)
Z <- Z 

array([False, False, False, False, False])

In [ ]:
#hide
Z = np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [ ]:
#hide
Z = np.arange(5)
#Z<Z>Z

28. 下列表达式的结果分别是什么

In [ ]:
#hide
print(np.array(0) / np.array(0))

nan


<ipython-input-35-8bbd6578ee43>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [ ]:
#hide
print(np.array(0) // np.array(0))

0


<ipython-input-36-9bb04709d645>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [ ]:
#hide
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29. 如何从零位对浮点数组做舍入

In [ ]:
#hide
Z = np.random.uniform(-10, 10, 10)
print(Z)
absZ = np.abs(Z)
print(absZ)
ceilZ = np.ceil(absZ)
print(ceilZ)
csZ = np.copysign(ceilZ, Z)
print(csZ)

[-3.46527404  7.03308927  2.08403936 -7.94790611 -2.62868924 -8.30040596
 -6.15592595  3.96862325 -2.63798098  2.36037931]
[3.46527404 7.03308927 2.08403936 7.94790611 2.62868924 8.30040596
 6.15592595 3.96862325 2.63798098 2.36037931]
[4. 8. 3. 8. 3. 9. 7. 4. 3. 3.]
[-4.  8.  3. -8. -3. -9. -7.  4. -3.  3.]


30. 如何找到两个数组中的共同元素

In [ ]:
#hide
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1,Z2))

[2 5 7 9]


31. 如何忽略所有的 numpy 警告

In [ ]:
#hide
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
np.seterr(all=None)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

32. 下面的表达式是正确的吗

In [ ]:
#hide
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. 如何得到昨天，今天，明天的日期

In [ ]:
#hide
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"yesterday is {yesterday}")
print(f"today is {today}")
print(f"tomorrow is {tomorrow}")

yesterday is 2020-03-24
today is 2020-03-25
tomorrow is 2020-03-26


34. 如何得到所有与2016年7月对应的日期

In [ ]:
#hide
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [ ]:
#hide
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分

In [ ]:
#hide
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z-1))
print(Z.astype(int))
print(np.trunc(Z))

[8. 6. 1. 3. 3. 8. 3. 7. 0. 1.]
[8. 6. 1. 3. 3. 8. 3. 7. 0. 1.]
[ 8.  6.  1.  3.  3.  8.  3.  7. -0.  1.]
[8 6 1 3 3 8 3 7 0 1]
[8. 6. 1. 3. 3. 8. 3. 7. 0. 1.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [ ]:
#hide
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [ ]:
#export
def generate():
    for x in range(10):
        yield x

In [ ]:
#hide
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
