In [ ]:
# default_exp numpycore

# numpy 100题

In [ ]:
#hide
from nbdev.showdoc import *

1. 导入numpy库并简写为 np

In [ ]:
#export
import numpy as np

2. 打印numpy的版本和配置说明

In [ ]:
#hide
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. 创建一个长度为10的空向量

In [ ]:
#hide
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小

In [ ]:
#hide
print(f"{Z.size * Z.itemsize:d} bytes")

80 bytes


5. 如何从命令行得到numpy中add函数的说明文档

In [ ]:
#hide
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

6. 创建一个长度为10并且除了第五个值为1的空向量

In [ ]:
#hide
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [ ]:
#hide
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. 反转一个向量(第一个元素变为最后一个) 

In [ ]:
#hide
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [ ]:
#hide
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [ ]:
#hide
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. 创建一个 3x3 的单位矩阵

In [ ]:
#hide
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组

In [ ]:
#hide
Z = np.random.random((3,3,3))
print(Z)

[[[0.70053062 0.26168163 0.59104621]
  [0.45899014 0.64685956 0.91216082]
  [0.11548299 0.84709555 0.70987871]]

 [[0.2440812  0.45018753 0.97623538]
  [0.77243068 0.13581932 0.87326543]
  [0.87662751 0.63395573 0.27743424]]

 [[0.24098181 0.38522176 0.61043025]
  [0.68645945 0.05061891 0.58302496]
  [0.64209293 0.50964101 0.98846839]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [ ]:
#hide
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(f"min:{Zmin} max:{Zmax}")

min:0.041280826759242384 max:0.9788945617322822


14. 创建一个长度为30的随机向量并找到它的平均值

In [ ]:
#hide
Z = np.random.random(30)
mean = Z.mean()
print(mean)

0.4700902125731784


15. 创建一个二维数组，其中边界值为1，其余值为0

In [ ]:
#hide
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在的数组，如何添加一个用0填充的边界

In [ ]:
#hide
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode="constant", constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么

In [ ]:
#hide
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [ ]:
#hide
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [ ]:
#hide
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么

In [ ]:
#hide
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [ ]:
#hide
Z = np.array([[0,1],[1,0]])
Z = np.tile(Z, (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化  
归一化:$（x-min）\div (max -min)$

In [ ]:
#hide
Z = np.random.random((5,5))
Zmax, Zmin = Z.min(), Z.max()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[ 0.23921647  0.91638775  0.67822158  0.19450341  0.30768855]
 [ 0.92766187  0.7307446   0.38645435  0.56692936  0.16489905]
 [ 0.42912895  0.56640922  0.44082318  0.47547442  0.53205011]
 [ 0.05636801  1.          0.36620115  0.56371604  0.83798273]
 [-0.          0.84173141  0.47654279  0.89628069  0.03139545]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义 dtype

In [ ]:
#hide
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [ ]:
#hide
Z = np.dot(np.ones((5,3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [ ]:
#hide
Z = np.arange(11)
Z[(3 < Z) & (8 >= Z)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么

In [ ]:
#hide
print(sum(range(5),-1))

9


In [ ]:
#hide
from numpy import *
print(sum(range(5),-1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个

In [ ]:
#hide
Z = np.arange(5)
Z ** Z

array([  1,   1,   4,  27, 256])

In [ ]:
#hide
Z = np.arange(5)
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [ ]:
#hide
Z = np.arange(5)
Z <- Z 

array([False, False, False, False, False])

In [ ]:
#hide
Z = np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [ ]:
#hide
Z = np.arange(5)
#Z<Z>Z

28. 下列表达式的结果分别是什么

In [ ]:
#hide
print(np.array(0) / np.array(0))

nan


In [ ]:
#hide
print(np.array(0) // np.array(0))

0


In [ ]:
#hide
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29. 如何从零位对浮点数组做舍入

In [ ]:
#hide
Z = np.random.uniform(-10, 10, 10)
print(Z)
absZ = np.abs(Z)
print(absZ)
ceilZ = np.ceil(absZ)
print(ceilZ)
csZ = np.copysign(ceilZ, Z)
print(csZ)

[ 1.15865366  4.50122091 -2.59854798  5.35299617 -3.44379335  2.47865482
 -1.74200667 -3.48991081 -0.52873098  3.70754007]
[1.15865366 4.50122091 2.59854798 5.35299617 3.44379335 2.47865482
 1.74200667 3.48991081 0.52873098 3.70754007]
[2. 5. 3. 6. 4. 3. 2. 4. 1. 4.]
[ 2.  5. -3.  6. -4.  3. -2. -4. -1.  4.]


30. 如何找到两个数组中的共同元素

In [ ]:
#hide
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1,Z2))

[0 1 5]


31. 如何忽略所有的 numpy 警告

In [ ]:
#hide
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
np.seterr(all=None)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

32. 下面的表达式是正确的吗

In [ ]:
#hide
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. 如何得到昨天，今天，明天的日期

In [ ]:
#hide
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"yesterday is {yesterday}")
print(f"today is {today}")
print(f"tomorrow is {tomorrow}")

yesterday is 2020-03-29
today is 2020-03-30
tomorrow is 2020-03-31


34. 如何得到所有与2016年7月对应的日期

In [ ]:
#hide
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [ ]:
#hide
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分

In [ ]:
#hide
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z-1))
print(Z.astype(int))
print(np.trunc(Z))

[7. 8. 5. 5. 5. 8. 3. 6. 8. 6.]
[7. 8. 5. 5. 5. 8. 3. 6. 8. 6.]
[7. 8. 5. 5. 5. 8. 3. 6. 8. 6.]
[7 8 5 5 5 8 3 6 8 6]
[7. 8. 5. 5. 5. 8. 3. 6. 8. 6.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [ ]:
#hide
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [ ]:
#export
def generate():
    for x in range(10):
        yield x

In [ ]:
#hide
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [ ]:
#hide
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序

In [ ]:
#hide
Z = np.random.random(10)
Z.sort()
print(Z)

[0.08661731 0.19227089 0.20847143 0.32186232 0.52472954 0.72138598
 0.80560292 0.80950457 0.82221435 0.9859824 ]


41. 对于一个小数组，如何用比 np.sum更快的方式对其求和

In [ ]:
#hide
Z = np.arange(10)
np.add.reduce(Z)

45

42. 对于两个随机数组A和B，检查它们是否相等

In [ ]:
#hide
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A, B)
print(equal)
equal = np.array_equal(A, B)
print(equal)

False
False


43. 创建一个只读数组(read-only)

In [ ]:
#hide
Z: ndarray = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [ ]:
#hide
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.8094475  1.26572586 0.04252866 0.21271533 0.77269752 0.60847935
 0.61653966 0.7732289  0.75477835 0.68006318]
[0.16078844 0.76070749 0.04959705 0.86921726 1.42718626 0.91636011
 1.01630129 1.18508359 1.44882008 1.05554346]


45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [ ]:
#hide
Z = np.random.random(10)
Z[Z.argmax()] = 1
print(Z)

[0.80594989 0.99619605 0.85538003 0.66117598 0.06495701 0.34514685
 0.67268842 1.         0.40753925 0.39429611]


46.  创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [ ]:
#hide
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [ ]:
#hide
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


48. 打印每个numpy标量类型的最小值和最大值

In [ ]:
#hide
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-1.189731495357231765e+4932
1.189731495357231765e+4932


49. 如何打印一个数组中的所有数值

In [ ]:
#hide
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. 给定标量时，如何找到数组中最接近标量的值

In [ ]:
#hide
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
Z[index]

14

51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [ ]:
#hide
Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),
                  ('color',    [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z.dtype)

[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])]


52. 对一个表示坐标形状为(10,2)的随机向量，找到点与点的距离

In [ ]:
#hide
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.26258841 0.44205818 0.71166107 0.38438414 0.04937197
  0.33060148 0.50957306 0.64070309 0.46796936]
 [0.26258841 0.         0.55898063 0.77419279 0.47398436 0.31122465
  0.27395669 0.67934296 0.7528892  0.63216169]
 [0.44205818 0.55898063 0.         0.28150264 0.09044905 0.42541228
  0.75541945 0.16176553 0.20071754 0.12208322]
 [0.71166107 0.77419279 0.28150264 0.         0.32753228 0.70095942
  1.00564576 0.33879944 0.15150999 0.33755639]
 [0.38438414 0.47398436 0.09044905 0.32753228 0.         0.37632219
  0.68354491 0.24490732 0.2791562  0.20020252]
 [0.04937197 0.31122465 0.42541228 0.70095942 0.37632219 0.
  0.3683887  0.4789375  0.62077314 0.43943076]
 [0.33060148 0.27395669 0.75541945 1.00564576 0.68354491 0.3683887
  0.         0.83880616 0.95613024 0.79594258]
 [0.50957306 0.67934296 0.16176553 0.33879944 0.24490732 0.4789375
  0.83880616 0.         0.19653627 0.04773289]
 [0.64070309 0.7528892  0.20071754 0.15150999 0.2791562  0.62077314
  0.95613024 0.1965362

53. 如何将32位的浮点数(float)转换为对应的整数(integer)

In [ ]:
#hide
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


54. 如何读取文件

55. 对于numpy数组，enumerate的等价操作是什么

In [ ]:
#hide
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print('-' * 8)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
--------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


$$
\boldsymbol{A}=\left[\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
a_{21} & a_{22} & \cdots & a_{2 n} \\
\vdots & \vdots & & \vdots \\
a_{m 1} & a_{m 2} & \cdots & a_{m n}
\end{array}\right], \quad a_{i j} \in \mathbb{R}
$$